### PR TITLE
issue_15: Add support of Error State

### LINKED ISSUE #15: Add support of Error State
In XComponent V5, when there's an unhandled exception in a triggered method, the xcruntime catches the exception and the corresponding state machine instance goes to a "built-in" error state. 
Add the possibility, to display this Error state in the spy. The inner exception should also be displayed.

### PR DESCRIPTION
**Pull request by mbarekh**
resolves #15

### CODE REVIEW

File: src/core.ts [hunk 1]
```diff
@@ -19,6 +19,7 @@ export const subscribeAllStateMachines = (dispatch: Dispatch<XCSpyState>, compon
                     continue;
                 ((stateMachine: string) => {
                     subscriber.subscribe(component, stateMachine, (data) => {
+                        console.error(data);
```
Comment (nicolaserny) [inline src/core.ts]: Do we need to log (in error) the data variable ?
